import { GraphQLClient } from 'graphql-request';
import Image from 'next/image'
import Head from 'next/head'


const graphcms = new GraphQLClient(
  'https://api-eu-central-1.graphcms.com/v2/ckq9gk2z9w8gk01z1gkgr97d9/master'
);

{/* Getting static props for each car, Each car detail will be desplayedd within its own page using slug as url */}
export async function getStaticProps({ params }) {
  const { car } = await graphcms.request(
    `
    query cars($slug: String!) {
      car(where: { slug: $slug }) {
        name
       description
       price
       acceleration
       power
       slug
       image {
         url
         width
         height
       }
       secondaryPicture {
         url
         width
         height
       }
      }
    }
  `,
    {
      slug: params.slug,
    }
  );

  return {
    props: {
      car
    },
  };
}

{/* Genetating static paths or URLs for each car that exists in GraphCMS */}
export async function getStaticPaths() {
  const { cars } = await graphcms.request(`
    {
      cars {
        slug
        name
      }
    }
  `);

  return {
    paths: cars.map(({ slug }) => ({
      params: { slug },
    })),
    fallback: false,
  };
}


export default function CarDetails({car}){
  return (
    <div>
    <Head>
      <title>{car.name}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
      <div className="car-card" >
        <Image
        layout="fill"
        objectFit="cover"
        src={car.image.url}
        //width={car.image.width}
        //height={car.image.height}
        />
      </div>

      <div className="wrapper">
        <div className="flex-h">
            <div className="flex-2-fr">
                <h1>{car.name}</h1>
                <p className="muted">{car.description}</p>
                <div className="mg-x-64">
                  <p className="muted">Price</p>
                  <h2>${car.price}</h2>

                  <p className="muted">Acceleration, 0-60 mph</p>
                  <h2>{car.acceleration} SEC</h2>

                  <p className="muted">Power</p>
                  <h2>{car.power} HP</h2>
                </div>

              </div>
            <div className="flex-1-fr">
            <Image
              src={car.secondaryPicture.url}
              width={car.secondaryPicture.width}
              height={car.secondaryPicture.height}
              >
              </Image>
            </div>
        </div>

      </div>
    </div>
  )
}
