import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { GraphQLClient, gql } from 'graphql-request';

export default function Home({cars}) {
  return (
    <div>
      <Head>
        <title>Mercedes-Benz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
          <h1>Welcome to the future</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque quis consequatur sit voluptatem perspiciatis, sunt. Doloribus accusamus fuga tempore, officiis beatae animi sit illum, debitis quidem quaerat quibusdam omnis quisquam.</p>
              {cars.map((car) => (
                <div key={car.id}>
                    <Image
                    src={car.image.url}
                    width={car.image.width}
                    height={car.image.height}
                    />
                    <h2>{car.name}</h2>
                    <Link  href={`/cars/${car.slug}`}>
                      <a>Read more</a>
                    </Link>
                </div>
              ))}
      </div>
    </div>
  )
}


export async function getStaticProps() {
  const graphcms = new GraphQLClient(
    'https://api-eu-central-1.graphcms.com/v2/ckq9gk2z9w8gk01z1gkgr97d9/master'
  );

  const { cars } = await graphcms.request(
    gql`
    {
      cars {
        id
        name
        description
        slug
        image {
          url
          fileName
          width
          height
        }
      }
    }
    `
  );

  return {
    props: {
      cars,
    },
  };
}
